"""MCP server exposing Lidarr's v1 REST API (OpenAPI 3.0.4) as tools.

Full coverage of every JSON-producing endpoint under /api/v1 plus GET /ping
(binary/text endpoints - media covers and raw log files - are excluded), but
exposed as ~15 resource-scoped *portmanteau* tools instead of one tool per
endpoint. Each portmanteau tool (e.g. lidarr_queue, lidarr_media_library)
takes an `operation` enum plus an `arguments` dict; see AGENTS.md for the
rationale (a 200+-tool server blows the MCP context budget on session start).

The vendored spec at tests/data/lidarr_openapi.json (develop HEAD
d88cbcec050c04b3064c9f36221edac152e241e2) still generates one async function
per endpoint into `_TOOL_REGISTRY` - keep it in sync with the spec (see
AGENTS.md). Those functions are no longer registered as individual MCP
tools; `_GROUPS` below buckets them by resource, and `_register_group` wraps
each bucket in a single dispatching tool that calls the right function by
name. Nothing about the endpoint functions themselves changes - grouping is
purely a registration-time concern.

Auth is the X-Api-Key header, generated in Lidarr > Settings > General >
Security. A group tool is marked readOnlyHint=True only when every operation
in it is a GET; mixed groups carry no hints (writes still get a `WRITE:` /
`DESTRUCTIVE:` note in their operation's doc line). Bodies are passed as
opaque dicts/lists. build_client points at the origin with no path suffix so
httpx joins the fully-qualified paths (including /ping) correctly.
"""

import inspect
import os
import sys
from typing import Any, Literal
from urllib.parse import quote

import httpx
from fastmcp import FastMCP
from fastmcp.exceptions import ToolError
from fastmcp.tools import Tool
from mcp.types import ToolAnnotations

READONLY = ToolAnnotations(readOnlyHint=True)
WRITE = ToolAnnotations(readOnlyHint=False, destructiveHint=False)
DESTRUCTIVE = ToolAnnotations(readOnlyHint=False, destructiveHint=True)

# Lidarr responses are plain JSON. `dict[str, Any]` (not bare `Any`) matters
# here: FastMCP needs a concrete schema to build MCP structured content, and
# skips that step entirely for an `Any` return type -- which silently makes
# Client.call_tool's `.data` come back None for any tool returning a JSON array
# (lidarr_list_artist and friends). Verified against fastmcp 3.4.7.
JSONObj = dict[str, Any]
JSONVal = JSONObj | list[Any]

mcp = FastMCP("lidarr-mcp")

_client: httpx.AsyncClient | None = None


def build_client(
    base_url: str, api_key: str | None, transport: httpx.BaseTransport | None = None
) -> httpx.AsyncClient:
    """Client pinned to the origin (no path suffix) so registered full paths
    like /api/v1/album and /ping both resolve correctly via httpx base join."""
    headers = {"X-Api-Key": api_key} if api_key else {}
    return httpx.AsyncClient(base_url=f"{base_url.rstrip('/')}", headers=headers, transport=transport)


async def _req(
    method: str,
    path: str,
    params: dict[str, Any] | None = None,
    json_body: JSONVal | None = None,
) -> JSONVal:
    assert _client is not None, "client not configured"
    r = await _client.request(method, path, params=params, json=json_body)
    if r.status_code >= 400:
        try:
            msg = r.json().get("message", r.text)
        except ValueError:
            msg = r.text
        raise ToolError(f"Lidarr API {r.status_code}: {msg}")
    if not r.text:
        return {}
    return r.json()


def _omit(params: dict[str, Any]) -> dict[str, Any]:
    """Drop keys whose values are empty/None so the API's defaults apply."""
    return {k: v for k, v in params.items() if v not in ("", None)}


# Resource groups for portmanteau registration. Every _TOOL_REGISTRY name
# must appear in exactly one group - see test_all_registry_names_grouped.

# REGISTRY
_TOOL_REGISTRY: list[dict[str, Any]] = [
 {'name': 'lidarr_list_album',
  'method': 'GET',
  'path': '/api/v1/album',
  'pp': [],
  'qp': [{'name': 'artist_id', 'wire': 'artistId', 'type': 'int', 'default': 'None'}, {'name': 'album_ids', 'wire': 'albumIds', 'type': 'list[Any]', 'default': 'None'}, {'name': 'foreign_album_id', 'wire': 'foreignAlbumId', 'type': 'str', 'default': 'None'}, {'name': 'include_all_artist_albums', 'wire': 'includeAllArtistAlbums', 'type': 'bool', 'default': 'False'}],
  'bk': 'none',
  'doc': 'List albums, optionally filtered by artist, album ids, or foreign album id. Query params: artist_id, album_ids, foreign_album_id, include_all_artist_albums.'},
 {'name': 'lidarr_add_album',
  'method': 'POST',
  'path': '/api/v1/album',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Add an album to a monitored artist (body is an AlbumResource). WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_get_album',
  'method': 'GET',
  'path': '/api/v1/album/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single album by id.'},
 {'name': 'lidarr_update_album',
  'method': 'PUT',
  'path': '/api/v1/album/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update an album (body is an AlbumResource). WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_delete_album',
  'method': 'DELETE',
  'path': '/api/v1/album/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [{'name': 'delete_files', 'wire': 'deleteFiles', 'type': 'bool', 'default': 'False'}, {'name': 'add_import_list_exclusion', 'wire': 'addImportListExclusion', 'type': 'bool', 'default': 'False'}],
  'bk': 'none',
  'doc': 'Delete an album. DESTRUCTIVE: this deletes data.'},
 {'name': 'lidarr_lookup_album',
  'method': 'GET',
  'path': '/api/v1/album/lookup',
  'pp': [],
  'qp': [{'name': 'term', 'wire': 'term', 'type': 'str', 'default': 'None'}],
  'bk': 'none',
  'doc': 'Look up albums by term or MusicBrainz id (MBID). Query params: term.'},
 {'name': 'lidarr_monitor_album',
  'method': 'PUT',
  'path': '/api/v1/album/monitor',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Set monitored state on multiple albums (body carries album ids). WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_update_albumstudio',
  'method': 'POST',
  'path': '/api/v1/albumstudio',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk studio operations across selected albums (tag, monitor, scan; body is an AlbumStudioResource). WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_list_artist',
  'method': 'GET',
  'path': '/api/v1/artist',
  'pp': [],
  'qp': [{'name': 'mb_id', 'wire': 'mbId', 'type': 'str', 'default': 'None'}],
  'bk': 'none',
  'doc': 'List all artists in the library, optionally filtered by MusicBrainz id. Query params: mb_id.'},
 {'name': 'lidarr_add_artist',
  'method': 'POST',
  'path': '/api/v1/artist',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Add a new artist from a lookup (body is an ArtistResource). WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_get_artist',
  'method': 'GET',
  'path': '/api/v1/artist/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single artist by id.'},
 {'name': 'lidarr_update_artist',
  'method': 'PUT',
  'path': '/api/v1/artist/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [{'name': 'move_files', 'wire': 'moveFiles', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Update an artist (body is an ArtistResource). WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_delete_artist',
  'method': 'DELETE',
  'path': '/api/v1/artist/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [{'name': 'delete_files', 'wire': 'deleteFiles', 'type': 'bool', 'default': 'False'}, {'name': 'add_import_list_exclusion', 'wire': 'addImportListExclusion', 'type': 'bool', 'default': 'False'}],
  'bk': 'none',
  'doc': 'Delete an artist, optionally deleting files or adding an import list exclusion. Query params: delete_files, add_import_list_exclusion. DESTRUCTIVE: this deletes data.'},
 {'name': 'lidarr_bulk_update_artist',
  'method': 'PUT',
  'path': '/api/v1/artist/editor',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk update artists (body is an ArtistEditorResource). WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_bulk_delete_artist',
  'method': 'DELETE',
  'path': '/api/v1/artist/editor',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk delete artists (body carries artist ids). DESTRUCTIVE: this deletes data.'},
 {'name': 'lidarr_lookup_artist',
  'method': 'GET',
  'path': '/api/v1/artist/lookup',
  'pp': [],
  'qp': [{'name': 'term', 'wire': 'term', 'type': 'str', 'default': 'None'}],
  'bk': 'none',
  'doc': 'Look up artists by term or MusicBrainz id (MBID). Query params: term.'},
 {'name': 'lidarr_list_autotagging',
  'method': 'GET',
  'path': '/api/v1/autotagging',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List auto tagging rules.'},
 {'name': 'lidarr_create_autotagging',
  'method': 'POST',
  'path': '/api/v1/autotagging',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create auto tagging rules (body is an AutoTaggingResource). WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_get_autotagging_schema',
  'method': 'GET',
  'path': '/api/v1/autotagging/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Return the auto tagging rules schema (available fields/options).'},
 {'name': 'lidarr_get_autotagging',
  'method': 'GET',
  'path': '/api/v1/autotagging/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single auto tagging rule by id.'},
 {'name': 'lidarr_update_autotagging',
  'method': 'PUT',
  'path': '/api/v1/autotagging/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update auto tagging rules. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_delete_autotagging',
  'method': 'DELETE',
  'path': '/api/v1/autotagging/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete auto tagging rules. DESTRUCTIVE: this deletes data.'},
 {'name': 'lidarr_list_blocklist',
  'method': 'GET',
  'path': '/api/v1/blocklist',
  'pp': [],
  'qp': [{'name': 'page', 'wire': 'page', 'type': 'int', 'default': '1'}, {'name': 'page_size', 'wire': 'pageSize', 'type': 'int', 'default': '10'}, {'name': 'sort_key', 'wire': 'sortKey', 'type': 'str', 'default': '""'}, {'name': 'sort_direction', 'wire': 'sortDirection', 'type': 'str', 'default': '""'}],
  'bk': 'none',
  'doc': 'List blocklisted releases. Query params: page, page_size, sort_key, sort_direction.'},
 {'name': 'lidarr_delete_blocklist',
  'method': 'DELETE',
  'path': '/api/v1/blocklist/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Remove a release from the blocklist. DESTRUCTIVE: this deletes data.'},
 {'name': 'lidarr_bulk_delete_blocklist',
  'method': 'DELETE',
  'path': '/api/v1/blocklist/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Remove multiple releases from the blocklist (body carries blocklist ids). DESTRUCTIVE: this deletes data.'},
 {'name': 'lidarr_list_calendar',
  'method': 'GET',
  'path': '/api/v1/calendar',
  'pp': [],
  'qp': [{'name': 'start', 'wire': 'start', 'type': 'str', 'default': 'None'}, {'name': 'end', 'wire': 'end', 'type': 'str', 'default': 'None'}, {'name': 'unmonitored', 'wire': 'unmonitored', 'type': 'bool', 'default': 'False'}, {'name': 'include_artist', 'wire': 'includeArtist', 'type': 'bool', 'default': 'False'}, {'name': 'tags', 'wire': 'tags', 'type': 'str', 'default': 'None'}],
  'bk': 'none',
  'doc': 'List albums releasing in a date range. Query params: start, end.'},
 {'name': 'lidarr_get_calendar',
  'method': 'GET',
  'path': '/api/v1/calendar/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single calendar entry (album) by id.'},
 {'name': 'lidarr_list_command',
  'method': 'GET',
  'path': '/api/v1/command',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List running and recent commands.'},
 {'name': 'lidarr_run_command',
  'method': 'POST',
  'path': '/api/v1/command',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Run a Lidarr command (body is a CommandResource with a name, e.g. RefreshArtist, RescanArtist, DownloadedAlbumsScan, RssSync, ApplicationUpdate). WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_get_command',
  'method': 'GET',
  'path': '/api/v1/command/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch the status of a single command by id.'},
 {'name': 'lidarr_delete_command',
  'method': 'DELETE',
  'path': '/api/v1/command/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Cancel a running command. DESTRUCTIVE: this deletes data.'},
 {'name': 'lidarr_get_config_downloadclient',
  'method': 'GET',
  'path': '/api/v1/config/downloadclient',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get download client global config.'},
 {'name': 'lidarr_get_config_downloadclient_by_id',
  'method': 'GET',
  'path': '/api/v1/config/downloadclient/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Get download client global config by id.'},
 {'name': 'lidarr_update_config_downloadclient',
  'method': 'PUT',
  'path': '/api/v1/config/downloadclient/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update download client global config. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_get_config_host',
  'method': 'GET',
  'path': '/api/v1/config/host',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get host/global config (port, url base, auth, logging).'},
 {'name': 'lidarr_get_config_host_by_id',
  'method': 'GET',
  'path': '/api/v1/config/host/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Get host config by id.'},
 {'name': 'lidarr_update_config_host',
  'method': 'PUT',
  'path': '/api/v1/config/host/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update host config. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_get_config_indexer',
  'method': 'GET',
  'path': '/api/v1/config/indexer',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get indexer global config (retention, priority, rss sync).'},
 {'name': 'lidarr_get_config_indexer_by_id',
  'method': 'GET',
  'path': '/api/v1/config/indexer/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Get indexer config by id.'},
 {'name': 'lidarr_update_config_indexer',
  'method': 'PUT',
  'path': '/api/v1/config/indexer/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update indexer config. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_get_config_mediamanagement',
  'method': 'GET',
  'path': '/api/v1/config/mediamanagement',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get media management config (root folder perms, recycle bin, file date).'},
 {'name': 'lidarr_get_config_mediamanagement_by_id',
  'method': 'GET',
  'path': '/api/v1/config/mediamanagement/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Get media management config by id.'},
 {'name': 'lidarr_update_config_mediamanagement',
  'method': 'PUT',
  'path': '/api/v1/config/mediamanagement/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update media management config. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_get_config_metadataprovider',
  'method': 'GET',
  'path': '/api/v1/config/metadataprovider',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get metadata provider config (MusicBrainz, rate limits).'},
 {'name': 'lidarr_get_config_metadataprovider_by_id',
  'method': 'GET',
  'path': '/api/v1/config/metadataprovider/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Get metadata provider config by id.'},
 {'name': 'lidarr_update_config_metadataprovider',
  'method': 'PUT',
  'path': '/api/v1/config/metadataprovider/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update metadata provider config. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_get_config_naming',
  'method': 'GET',
  'path': '/api/v1/config/naming',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get track/album naming config.'},
 {'name': 'lidarr_get_config_naming_by_id',
  'method': 'GET',
  'path': '/api/v1/config/naming/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Get naming config by id.'},
 {'name': 'lidarr_update_config_naming',
  'method': 'PUT',
  'path': '/api/v1/config/naming/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update naming config. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_list_config_naming_examples',
  'method': 'GET',
  'path': '/api/v1/config/naming/examples',
  'pp': [],
  'qp': [{'name': 'rename_tracks', 'wire': 'renameTracks', 'type': 'bool', 'default': 'False'}, {'name': 'replace_illegal_characters', 'wire': 'replaceIllegalCharacters', 'type': 'bool', 'default': 'False'}, {'name': 'colon_replacement_format', 'wire': 'colonReplacementFormat', 'type': 'int', 'default': 'None'}, {'name': 'standard_track_format', 'wire': 'standardTrackFormat', 'type': 'str', 'default': 'None'}, {'name': 'multi_disc_track_format', 'wire': 'multiDiscTrackFormat', 'type': 'str', 'default': 'None'}, {'name': 'artist_folder_format', 'wire': 'artistFolderFormat', 'type': 'str', 'default': 'None'}, {'name': 'include_artist_name', 'wire': 'includeArtistName', 'type': 'bool', 'default': 'False'}, {'name': 'include_album_title', 'wire': 'includeAlbumTitle', 'type': 'bool', 'default': 'False'}, {'name': 'include_quality', 'wire': 'includeQuality', 'type': 'bool', 'default': 'False'}, {'name': 'replace_spaces', 'wire': 'replaceSpaces', 'type': 'bool', 'default': 'False'}, {'name': 'separator', 'wire': 'separator', 'type': 'str', 'default': 'None'}, {'name': 'number_style', 'wire': 'numberStyle', 'type': 'str', 'default': 'None'}, {'name': 'id', 'wire': 'id', 'type': 'int', 'default': 'None'}, {'name': 'resource_name', 'wire': 'resourceName', 'type': 'str', 'default': 'None'}],
  'bk': 'none',
  'doc': 'Render naming examples based on the current config.'},
 {'name': 'lidarr_get_config_ui',
  'method': 'GET',
  'path': '/api/v1/config/ui',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get UI config (calendar, dates, theme).'},
 {'name': 'lidarr_get_config_ui_by_id',
  'method': 'GET',
  'path': '/api/v1/config/ui/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Get UI config by id.'},
 {'name': 'lidarr_update_config_ui',
  'method': 'PUT',
  'path': '/api/v1/config/ui/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update UI config. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_list_customfilter',
  'method': 'GET',
  'path': '/api/v1/customfilter',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List saved custom filters.'},
 {'name': 'lidarr_create_customfilter',
  'method': 'POST',
  'path': '/api/v1/customfilter',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create a custom filter. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_get_customfilter',
  'method': 'GET',
  'path': '/api/v1/customfilter/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single custom filter by id.'},
 {'name': 'lidarr_update_customfilter',
  'method': 'PUT',
  'path': '/api/v1/customfilter/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update a custom filter. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_delete_customfilter',
  'method': 'DELETE',
  'path': '/api/v1/customfilter/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete a custom filter. DESTRUCTIVE: this deletes data.'},
 {'name': 'lidarr_list_customformat',
  'method': 'GET',
  'path': '/api/v1/customformat',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List custom formats.'},
 {'name': 'lidarr_create_customformat',
  'method': 'POST',
  'path': '/api/v1/customformat',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create a custom format. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_get_customformat_schema',
  'method': 'GET',
  'path': '/api/v1/customformat/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Return the custom format schema (available specifications).'},
 {'name': 'lidarr_get_customformat',
  'method': 'GET',
  'path': '/api/v1/customformat/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single custom format by id.'},
 {'name': 'lidarr_update_customformat',
  'method': 'PUT',
  'path': '/api/v1/customformat/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update a custom format. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_delete_customformat',
  'method': 'DELETE',
  'path': '/api/v1/customformat/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete a custom format. DESTRUCTIVE: this deletes data.'},
 {'name': 'lidarr_bulk_update_customformat',
  'method': 'PUT',
  'path': '/api/v1/customformat/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk update custom formats (body is a list of resources). WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_bulk_delete_customformat',
  'method': 'DELETE',
  'path': '/api/v1/customformat/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk delete custom formats (body carries custom format ids). DESTRUCTIVE: this deletes data.'},
 {'name': 'lidarr_list_delayprofile',
  'method': 'GET',
  'path': '/api/v1/delayprofile',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List delay profiles.'},
 {'name': 'lidarr_create_delayprofile',
  'method': 'POST',
  'path': '/api/v1/delayprofile',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create a delay profile. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_get_delayprofile',
  'method': 'GET',
  'path': '/api/v1/delayprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single delay profile by id.'},
 {'name': 'lidarr_update_delayprofile',
  'method': 'PUT',
  'path': '/api/v1/delayprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update a delay profile. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_delete_delayprofile',
  'method': 'DELETE',
  'path': '/api/v1/delayprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete a delay profile. DESTRUCTIVE: this deletes data.'},
 {'name': 'lidarr_reorder_delayprofile',
  'method': 'PUT',
  'path': '/api/v1/delayprofile/reorder/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [{'name': 'after_id', 'wire': 'afterId', 'type': 'int', 'default': 'None'}],
  'bk': 'none',
  'doc': 'Reorder delay profiles (move the profile with this id to a new order). Query params: after. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_get_diskspace',
  'method': 'GET',
  'path': '/api/v1/diskspace',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get disk free space for all root folders.'},
 {'name': 'lidarr_list_downloadclient',
  'method': 'GET',
  'path': '/api/v1/downloadclient',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List download clients.'},
 {'name': 'lidarr_create_downloadclient',
  'method': 'POST',
  'path': '/api/v1/downloadclient',
  'pp': [],
  'qp': [{'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Add a download client (body is a DownloadClientResource). WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_get_downloadclient',
  'method': 'GET',
  'path': '/api/v1/downloadclient/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single download client by id.'},
 {'name': 'lidarr_update_downloadclient',
  'method': 'PUT',
  'path': '/api/v1/downloadclient/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [{'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Update a download client. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_delete_downloadclient',
  'method': 'DELETE',
  'path': '/api/v1/downloadclient/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete a download client. DESTRUCTIVE: this deletes data.'},
 {'name': 'lidarr_get_downloadclient_schema',
  'method': 'GET',
  'path': '/api/v1/downloadclient/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Return the download client schema (available implementations).'},
 {'name': 'lidarr_test_downloadclient',
  'method': 'POST',
  'path': '/api/v1/downloadclient/test',
  'pp': [],
  'qp': [{'name': 'force_test', 'wire': 'forceTest', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Test a download client configuration (body, without saving). WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_test_all_downloadclient',
  'method': 'POST',
  'path': '/api/v1/downloadclient/testall',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Test all download clients. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_action_downloadclient',
  'method': 'POST',
  'path': '/api/v1/downloadclient/action/{name}',
  'pp': [{'name': 'name', 'wire': 'name', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Run a download client provider-specific action. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_bulk_update_downloadclient',
  'method': 'PUT',
  'path': '/api/v1/downloadclient/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk update download clients (body is a list of resources). WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_bulk_delete_downloadclient',
  'method': 'DELETE',
  'path': '/api/v1/downloadclient/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk delete download clients (body carries ids). DESTRUCTIVE: this deletes data.'},
 {'name': 'lidarr_list_filesystem',
  'method': 'GET',
  'path': '/api/v1/filesystem',
  'pp': [],
  'qp': [{'name': 'path', 'wire': 'path', 'type': 'str', 'default': 'None'}, {'name': 'include_files', 'wire': 'includeFiles', 'type': 'bool', 'default': 'False'}, {'name': 'allow_folders_without_trailing_slashes', 'wire': 'allowFoldersWithoutTrailingSlashes', 'type': 'bool', 'default': 'False'}],
  'bk': 'none',
  'doc': 'List directories and files for a path. Query params: path, include_files, allow_folders_without_trailing_slashes.'},
 {'name': 'lidarr_list_filesystem_type',
  'method': 'GET',
  'path': '/api/v1/filesystem/type',
  'pp': [],
  'qp': [{'name': 'path', 'wire': 'path', 'type': 'str', 'default': 'None'}],
  'bk': 'none',
  'doc': 'Get the filesystem entity type for a path. Query params: path.'},
 {'name': 'lidarr_list_filesystem_mediafiles',
  'method': 'GET',
  'path': '/api/v1/filesystem/mediafiles',
  'pp': [],
  'qp': [{'name': 'path', 'wire': 'path', 'type': 'str', 'default': 'None'}],
  'bk': 'none',
  'doc': 'List media files in a path. Query params: path.'},
 {'name': 'lidarr_get_health',
  'method': 'GET',
  'path': '/api/v1/health',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List health checks (warnings/errors).'},
 {'name': 'lidarr_list_history',
  'method': 'GET',
  'path': '/api/v1/history',
  'pp': [],
  'qp': [{'name': 'page', 'wire': 'page', 'type': 'int', 'default': '1'}, {'name': 'page_size', 'wire': 'pageSize', 'type': 'int', 'default': '10'}, {'name': 'sort_key', 'wire': 'sortKey', 'type': 'str', 'default': '""'}, {'name': 'sort_direction', 'wire': 'sortDirection', 'type': 'str', 'default': '""'}, {'name': 'include_artist', 'wire': 'includeArtist', 'type': 'bool', 'default': 'False'}, {'name': 'include_album', 'wire': 'includeAlbum', 'type': 'bool', 'default': 'False'}, {'name': 'include_track', 'wire': 'includeTrack', 'type': 'bool', 'default': 'False'}, {'name': 'event_type', 'wire': 'eventType', 'type': 'list[Any]', 'default': 'None'}, {'name': 'album_id', 'wire': 'albumId', 'type': 'int', 'default': 'None'}, {'name': 'download_id', 'wire': 'downloadId', 'type': 'str', 'default': 'None'}, {'name': 'artist_ids', 'wire': 'artistIds', 'type': 'list[Any]', 'default': 'None'}, {'name': 'quality', 'wire': 'quality', 'type': 'list[Any]', 'default': 'None'}],
  'bk': 'none',
  'doc': 'Paged history of grabs and imports. Query params: page, page_size, sort_key, sort_direction, include_artist, include_album, include_track, event_type, album_id, download_id, artist_ids, quality.'},
 {'name': 'lidarr_list_history_since',
  'method': 'GET',
  'path': '/api/v1/history/since',
  'pp': [],
  'qp': [{'name': 'date', 'wire': 'date', 'type': 'str', 'default': 'None'}, {'name': 'event_type', 'wire': 'eventType', 'type': 'str', 'default': 'None'}, {'name': 'include_artist', 'wire': 'includeArtist', 'type': 'bool', 'default': 'False'}, {'name': 'include_album', 'wire': 'includeAlbum', 'type': 'bool', 'default': 'False'}, {'name': 'include_track', 'wire': 'includeTrack', 'type': 'bool', 'default': 'False'}],
  'bk': 'none',
  'doc': 'History since a date, optionally filtered by artist. Query params: date, artist_id, event_type, include_artist, include_album, include_track.'},
 {'name': 'lidarr_list_history_artist',
  'method': 'GET',
  'path': '/api/v1/history/artist',
  'pp': [],
  'qp': [{'name': 'artist_id', 'wire': 'artistId', 'type': 'int', 'default': 'None'}, {'name': 'album_id', 'wire': 'albumId', 'type': 'int', 'default': 'None'}, {'name': 'event_type', 'wire': 'eventType', 'type': 'str', 'default': 'None'}, {'name': 'include_artist', 'wire': 'includeArtist', 'type': 'bool', 'default': 'False'}, {'name': 'include_album', 'wire': 'includeAlbum', 'type': 'bool', 'default': 'False'}, {'name': 'include_track', 'wire': 'includeTrack', 'type': 'bool', 'default': 'False'}],
  'bk': 'none',
  'doc': 'Recent history grouped by artist. Query params: sort_key, page, page_size, include_artist, include_album, include_track.'},
 {'name': 'lidarr_mark_history_item_failed',
  'method': 'POST',
  'path': '/api/v1/history/failed/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Mark a grabbed history item as failed. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_list_importlist',
  'method': 'GET',
  'path': '/api/v1/importlist',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List import lists.'},
 {'name': 'lidarr_create_importlist',
  'method': 'POST',
  'path': '/api/v1/importlist',
  'pp': [],
  'qp': [{'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Add an import list (body is an ImportListResource). WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_get_importlist',
  'method': 'GET',
  'path': '/api/v1/importlist/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single import list by id.'},
 {'name': 'lidarr_update_importlist',
  'method': 'PUT',
  'path': '/api/v1/importlist/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [{'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Update an import list. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_delete_importlist',
  'method': 'DELETE',
  'path': '/api/v1/importlist/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete an import list. DESTRUCTIVE: this deletes data.'},
 {'name': 'lidarr_get_importlist_schema',
  'method': 'GET',
  'path': '/api/v1/importlist/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Return the import list schema (available implementations).'},
 {'name': 'lidarr_test_importlist',
  'method': 'POST',
  'path': '/api/v1/importlist/test',
  'pp': [],
  'qp': [{'name': 'force_test', 'wire': 'forceTest', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Test an import list configuration (body, without saving). WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_test_all_importlist',
  'method': 'POST',
  'path': '/api/v1/importlist/testall',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Test all import lists. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_action_importlist',
  'method': 'POST',
  'path': '/api/v1/importlist/action/{name}',
  'pp': [{'name': 'name', 'wire': 'name', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Run an import list provider-specific action. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_bulk_update_importlist',
  'method': 'PUT',
  'path': '/api/v1/importlist/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk update import lists (body is a list of resources). WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_bulk_delete_importlist',
  'method': 'DELETE',
  'path': '/api/v1/importlist/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk delete import lists (body carries ids). DESTRUCTIVE: this deletes data.'},
 {'name': 'lidarr_list_importlistexclusion',
  'method': 'GET',
  'path': '/api/v1/importlistexclusion',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List import list exclusions.'},
 {'name': 'lidarr_create_importlistexclusion',
  'method': 'POST',
  'path': '/api/v1/importlistexclusion',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create an import list exclusion. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_get_importlistexclusion',
  'method': 'GET',
  'path': '/api/v1/importlistexclusion/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single import list exclusion by id.'},
 {'name': 'lidarr_update_importlistexclusion',
  'method': 'PUT',
  'path': '/api/v1/importlistexclusion/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update an import list exclusion. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_delete_importlistexclusion',
  'method': 'DELETE',
  'path': '/api/v1/importlistexclusion/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete an import list exclusion. DESTRUCTIVE: this deletes data.'},
 {'name': 'lidarr_list_indexer',
  'method': 'GET',
  'path': '/api/v1/indexer',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List indexers.'},
 {'name': 'lidarr_create_indexer',
  'method': 'POST',
  'path': '/api/v1/indexer',
  'pp': [],
  'qp': [{'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Add an indexer (body is an IndexerResource). WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_get_indexer',
  'method': 'GET',
  'path': '/api/v1/indexer/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single indexer by id.'},
 {'name': 'lidarr_update_indexer',
  'method': 'PUT',
  'path': '/api/v1/indexer/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [{'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Update an indexer. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_delete_indexer',
  'method': 'DELETE',
  'path': '/api/v1/indexer/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete an indexer. DESTRUCTIVE: this deletes data.'},
 {'name': 'lidarr_get_indexer_schema',
  'method': 'GET',
  'path': '/api/v1/indexer/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Return the indexer schema (available implementations).'},
 {'name': 'lidarr_test_indexer',
  'method': 'POST',
  'path': '/api/v1/indexer/test',
  'pp': [],
  'qp': [{'name': 'force_test', 'wire': 'forceTest', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Test an indexer configuration (body, without saving). WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_test_all_indexer',
  'method': 'POST',
  'path': '/api/v1/indexer/testall',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Test all enabled indexers. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_action_indexer',
  'method': 'POST',
  'path': '/api/v1/indexer/action/{name}',
  'pp': [{'name': 'name', 'wire': 'name', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Run an indexer provider-specific action (e.g. search, getCookies). WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_bulk_update_indexer',
  'method': 'PUT',
  'path': '/api/v1/indexer/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk update indexers (body is a list of resources). WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_bulk_delete_indexer',
  'method': 'DELETE',
  'path': '/api/v1/indexer/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk delete indexers (body carries ids). DESTRUCTIVE: this deletes data.'},
 {'name': 'lidarr_get_indexerflag',
  'method': 'GET',
  'path': '/api/v1/indexerflag',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List indexer flags.'},
 {'name': 'lidarr_list_language',
  'method': 'GET',
  'path': '/api/v1/language',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List all languages.'},
 {'name': 'lidarr_get_language',
  'method': 'GET',
  'path': '/api/v1/language/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single language by id.'},
 {'name': 'lidarr_list_localization',
  'method': 'GET',
  'path': '/api/v1/localization',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get the localization strings dictionary.'},
 {'name': 'lidarr_list_log',
  'method': 'GET',
  'path': '/api/v1/log',
  'pp': [],
  'qp': [{'name': 'page', 'wire': 'page', 'type': 'int', 'default': '1'}, {'name': 'page_size', 'wire': 'pageSize', 'type': 'int', 'default': '10'}, {'name': 'sort_key', 'wire': 'sortKey', 'type': 'str', 'default': '""'}, {'name': 'sort_direction', 'wire': 'sortDirection', 'type': 'str', 'default': '""'}, {'name': 'level', 'wire': 'level', 'type': 'str', 'default': 'None'}],
  'bk': 'none',
  'doc': 'Paged log entries, filtered by level. Query params: page, page_size, sort_key, sort_direction, level.'},
 {'name': 'lidarr_list_log_file',
  'method': 'GET',
  'path': '/api/v1/log/file',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List available log files.'},
 {'name': 'lidarr_list_log_file_update',
  'method': 'GET',
  'path': '/api/v1/log/file/update',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List available update log files.'},
 {'name': 'lidarr_list_manualimport',
  'method': 'GET',
  'path': '/api/v1/manualimport',
  'pp': [],
  'qp': [{'name': 'folder', 'wire': 'folder', 'type': 'str', 'default': 'None'}, {'name': 'download_id', 'wire': 'downloadId', 'type': 'str', 'default': 'None'}, {'name': 'artist_id', 'wire': 'artistId', 'type': 'int', 'default': 'None'}, {'name': 'filter_existing_files', 'wire': 'filterExistingFiles', 'type': 'bool', 'default': 'True'}, {'name': 'replace_existing_files', 'wire': 'replaceExistingFiles', 'type': 'bool', 'default': 'True'}],
  'bk': 'none',
  'doc': 'List files available for manual import from a folder. Query params: folder, download_id, artist_id, filter_existing_files.'},
 {'name': 'lidarr_commit_manual_import',
  'method': 'POST',
  'path': '/api/v1/manualimport',
  'pp': [],
  'qp': [],
  'bk': 'list',
  'doc': 'Submit manual import decisions (body is a list of manual import resources). WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_list_metadata',
  'method': 'GET',
  'path': '/api/v1/metadata',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List metadata consumers (Kodi, Plex, Emby NFO writers).'},
 {'name': 'lidarr_create_metadata',
  'method': 'POST',
  'path': '/api/v1/metadata',
  'pp': [],
  'qp': [{'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Add a metadata consumer (body is a MetadataResource). WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_get_metadata',
  'method': 'GET',
  'path': '/api/v1/metadata/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single metadata consumer by id.'},
 {'name': 'lidarr_update_metadata',
  'method': 'PUT',
  'path': '/api/v1/metadata/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [{'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Update a metadata consumer. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_delete_metadata',
  'method': 'DELETE',
  'path': '/api/v1/metadata/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete a metadata consumer. DESTRUCTIVE: this deletes data.'},
 {'name': 'lidarr_get_metadata_schema',
  'method': 'GET',
  'path': '/api/v1/metadata/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Return the metadata consumer schema (available implementations).'},
 {'name': 'lidarr_test_metadata',
  'method': 'POST',
  'path': '/api/v1/metadata/test',
  'pp': [],
  'qp': [{'name': 'force_test', 'wire': 'forceTest', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Test a metadata consumer configuration (body, without saving). WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_test_all_metadata',
  'method': 'POST',
  'path': '/api/v1/metadata/testall',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Test all metadata consumers. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_action_metadata',
  'method': 'POST',
  'path': '/api/v1/metadata/action/{name}',
  'pp': [{'name': 'name', 'wire': 'name', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Run a metadata consumer provider-specific action. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_list_metadataprofile',
  'method': 'GET',
  'path': '/api/v1/metadataprofile',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List metadata profiles (MusicBrainz release-status/type filters).'},
 {'name': 'lidarr_create_metadataprofile',
  'method': 'POST',
  'path': '/api/v1/metadataprofile',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create a metadata profile. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_get_metadataprofile',
  'method': 'GET',
  'path': '/api/v1/metadataprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single metadata profile by id.'},
 {'name': 'lidarr_update_metadataprofile',
  'method': 'PUT',
  'path': '/api/v1/metadataprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update a metadata profile. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_delete_metadataprofile',
  'method': 'DELETE',
  'path': '/api/v1/metadataprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete a metadata profile. DESTRUCTIVE: this deletes data.'},
 {'name': 'lidarr_get_metadataprofile_schema',
  'method': 'GET',
  'path': '/api/v1/metadataprofile/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Return the metadata profile schema (available primary types/release statuses).'},
 {'name': 'lidarr_list_notification',
  'method': 'GET',
  'path': '/api/v1/notification',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List notifications.'},
 {'name': 'lidarr_create_notification',
  'method': 'POST',
  'path': '/api/v1/notification',
  'pp': [],
  'qp': [{'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Add a notification (body is a NotificationResource). WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_get_notification',
  'method': 'GET',
  'path': '/api/v1/notification/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single notification by id.'},
 {'name': 'lidarr_update_notification',
  'method': 'PUT',
  'path': '/api/v1/notification/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [{'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Update a notification. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_delete_notification',
  'method': 'DELETE',
  'path': '/api/v1/notification/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete a notification. DESTRUCTIVE: this deletes data.'},
 {'name': 'lidarr_get_notification_schema',
  'method': 'GET',
  'path': '/api/v1/notification/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Return the notification schema (available implementations).'},
 {'name': 'lidarr_test_notification',
  'method': 'POST',
  'path': '/api/v1/notification/test',
  'pp': [],
  'qp': [{'name': 'force_test', 'wire': 'forceTest', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Test a notification configuration (body, without saving). WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_test_all_notification',
  'method': 'POST',
  'path': '/api/v1/notification/testall',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Test all notifications. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_action_notification',
  'method': 'POST',
  'path': '/api/v1/notification/action/{name}',
  'pp': [{'name': 'name', 'wire': 'name', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Run a notification provider-specific action. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_get_parse',
  'method': 'GET',
  'path': '/api/v1/parse',
  'pp': [],
  'qp': [{'name': 'title', 'wire': 'title', 'type': 'str', 'default': 'None'}],
  'bk': 'none',
  'doc': 'Parse a release title into artist/album/track/quality. Query params: title.'},
 {'name': 'lidarr_ping',
  'method': 'GET',
  'path': '/ping',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Ping the server to verify it is reachable and authenticated.'},
 {'name': 'lidarr_list_qualitydefinition',
  'method': 'GET',
  'path': '/api/v1/qualitydefinition',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List quality definitions (per quality: title, weight, min/max size).'},
 {'name': 'lidarr_get_qualitydefinition',
  'method': 'GET',
  'path': '/api/v1/qualitydefinition/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single quality definition by id.'},
 {'name': 'lidarr_update_qualitydefinition',
  'method': 'PUT',
  'path': '/api/v1/qualitydefinition/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update a single quality definition. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_update_quality_definitions',
  'method': 'PUT',
  'path': '/api/v1/qualitydefinition/update',
  'pp': [],
  'qp': [],
  'bk': 'list',
  'doc': 'Bulk update quality definitions (body is a list of resources). WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_list_qualityprofile',
  'method': 'GET',
  'path': '/api/v1/qualityprofile',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List quality profiles.'},
 {'name': 'lidarr_create_qualityprofile',
  'method': 'POST',
  'path': '/api/v1/qualityprofile',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create a quality profile. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_get_qualityprofile',
  'method': 'GET',
  'path': '/api/v1/qualityprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single quality profile by id.'},
 {'name': 'lidarr_update_qualityprofile',
  'method': 'PUT',
  'path': '/api/v1/qualityprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update a quality profile. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_delete_qualityprofile',
  'method': 'DELETE',
  'path': '/api/v1/qualityprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete a quality profile. DESTRUCTIVE: this deletes data.'},
 {'name': 'lidarr_get_qualityprofile_schema',
  'method': 'GET',
  'path': '/api/v1/qualityprofile/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Return the quality profile creation schema.'},
 {'name': 'lidarr_list_queue',
  'method': 'GET',
  'path': '/api/v1/queue',
  'pp': [],
  'qp': [{'name': 'page', 'wire': 'page', 'type': 'int', 'default': '1'}, {'name': 'page_size', 'wire': 'pageSize', 'type': 'int', 'default': '10'}, {'name': 'sort_key', 'wire': 'sortKey', 'type': 'str', 'default': '""'}, {'name': 'sort_direction', 'wire': 'sortDirection', 'type': 'str', 'default': '""'}, {'name': 'include_unknown_artist_items', 'wire': 'includeUnknownArtistItems', 'type': 'bool', 'default': 'False'}, {'name': 'include_artist', 'wire': 'includeArtist', 'type': 'bool', 'default': 'False'}, {'name': 'include_album', 'wire': 'includeAlbum', 'type': 'bool', 'default': 'False'}, {'name': 'artist_ids', 'wire': 'artistIds', 'type': 'list[Any]', 'default': 'None'}, {'name': 'protocol', 'wire': 'protocol', 'type': 'str', 'default': 'None'}, {'name': 'quality', 'wire': 'quality', 'type': 'list[Any]', 'default': 'None'}],
  'bk': 'none',
  'doc': 'Paged download queue. Query params: page, page_size, sort_key, sort_direction, include_unknown_artist_items, include_artist, include_album, artist_ids, protocol, quality.'},
 {'name': 'lidarr_get_queue_details',
  'method': 'GET',
  'path': '/api/v1/queue/details',
  'pp': [],
  'qp': [{'name': 'artist_id', 'wire': 'artistId', 'type': 'int', 'default': 'None'}, {'name': 'album_ids', 'wire': 'albumIds', 'type': 'list[Any]', 'default': 'None'}, {'name': 'include_artist', 'wire': 'includeArtist', 'type': 'bool', 'default': 'False'}, {'name': 'include_album', 'wire': 'includeAlbum', 'type': 'bool', 'default': 'True'}],
  'bk': 'none',
  'doc': 'Full download queue with all detail, unpaged.'},
 {'name': 'lidarr_get_queue_status',
  'method': 'GET',
  'path': '/api/v1/queue/status',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Queue summary and status counts.'},
 {'name': 'lidarr_grab_queue_item',
  'method': 'POST',
  'path': '/api/v1/queue/grab/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Force-grab a queued release. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_grab_queue_bulk',
  'method': 'POST',
  'path': '/api/v1/queue/grab/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Force-grab multiple queued releases (body carries queue item ids). WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_delete_queue',
  'method': 'DELETE',
  'path': '/api/v1/queue/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [{'name': 'remove_from_client', 'wire': 'removeFromClient', 'type': 'bool', 'default': 'True'}, {'name': 'blocklist', 'wire': 'blocklist', 'type': 'bool', 'default': 'False'}, {'name': 'skip_redownload', 'wire': 'skipRedownload', 'type': 'bool', 'default': 'False'}, {'name': 'change_category', 'wire': 'changeCategory', 'type': 'bool', 'default': 'False'}],
  'bk': 'none',
  'doc': 'Remove a queue item, optionally adding it to the blocklist. Query params: blocklist, skip_redownload. DESTRUCTIVE: this deletes data.'},
 {'name': 'lidarr_bulk_delete_queue',
  'method': 'DELETE',
  'path': '/api/v1/queue/bulk',
  'pp': [],
  'qp': [{'name': 'remove_from_client', 'wire': 'removeFromClient', 'type': 'bool', 'default': 'True'}, {'name': 'blocklist', 'wire': 'blocklist', 'type': 'bool', 'default': 'False'}, {'name': 'skip_redownload', 'wire': 'skipRedownload', 'type': 'bool', 'default': 'False'}, {'name': 'change_category', 'wire': 'changeCategory', 'type': 'bool', 'default': 'False'}],
  'bk': 'dict',
  'doc': 'Bulk remove queue items (body carries queue item ids). Query params: blocklist, skip_redownload. DESTRUCTIVE: this deletes data.'},
 {'name': 'lidarr_list_release',
  'method': 'GET',
  'path': '/api/v1/release',
  'pp': [],
  'qp': [{'name': 'album_id', 'wire': 'albumId', 'type': 'int', 'default': 'None'}, {'name': 'artist_id', 'wire': 'artistId', 'type': 'int', 'default': 'None'}],
  'bk': 'none',
  'doc': 'List release search results for an album (for manual download). Query params: album_id.'},
 {'name': 'lidarr_download_release',
  'method': 'POST',
  'path': '/api/v1/release',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Download a chosen release (body is a ReleaseResource). WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_push_release',
  'method': 'POST',
  'path': '/api/v1/release/push',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Push a release URL/torrent to the download client. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_list_releaseprofile',
  'method': 'GET',
  'path': '/api/v1/releaseprofile',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List release profiles (preferred/ignored terms).'},
 {'name': 'lidarr_create_releaseprofile',
  'method': 'POST',
  'path': '/api/v1/releaseprofile',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create a release profile. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_get_releaseprofile',
  'method': 'GET',
  'path': '/api/v1/releaseprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single release profile by id.'},
 {'name': 'lidarr_update_releaseprofile',
  'method': 'PUT',
  'path': '/api/v1/releaseprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update a release profile. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_delete_releaseprofile',
  'method': 'DELETE',
  'path': '/api/v1/releaseprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete a release profile. DESTRUCTIVE: this deletes data.'},
 {'name': 'lidarr_list_remotepathmapping',
  'method': 'GET',
  'path': '/api/v1/remotepathmapping',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List remote path mappings.'},
 {'name': 'lidarr_create_remotepathmapping',
  'method': 'POST',
  'path': '/api/v1/remotepathmapping',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create a remote path mapping. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_get_remotepathmapping',
  'method': 'GET',
  'path': '/api/v1/remotepathmapping/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single remote path mapping by id.'},
 {'name': 'lidarr_update_remotepathmapping',
  'method': 'PUT',
  'path': '/api/v1/remotepathmapping/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update a remote path mapping. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_delete_remotepathmapping',
  'method': 'DELETE',
  'path': '/api/v1/remotepathmapping/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete a remote path mapping. DESTRUCTIVE: this deletes data.'},
 {'name': 'lidarr_get_rename',
  'method': 'GET',
  'path': '/api/v1/rename',
  'pp': [],
  'qp': [{'name': 'artist_id', 'wire': 'artistId', 'type': 'int', 'default': 'None'}, {'name': 'album_id', 'wire': 'albumId', 'type': 'int', 'default': 'None'}],
  'bk': 'none',
  'doc': 'Preview track renames for the given artists/albums. Query params: artist_ids, album_ids.'},
 {'name': 'lidarr_get_retag',
  'method': 'GET',
  'path': '/api/v1/retag',
  'pp': [],
  'qp': [{'name': 'artist_id', 'wire': 'artistId', 'type': 'int', 'default': 'None'}, {'name': 'album_id', 'wire': 'albumId', 'type': 'int', 'default': 'None'}],
  'bk': 'none',
  'doc': 'Preview track file metadata retags. Query params: artist_ids, album_ids.'},
 {'name': 'lidarr_list_rootfolder',
  'method': 'GET',
  'path': '/api/v1/rootfolder',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List root folders (with free space and default profile ids).'},
 {'name': 'lidarr_create_rootfolder',
  'method': 'POST',
  'path': '/api/v1/rootfolder',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Add a root folder. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_get_rootfolder',
  'method': 'GET',
  'path': '/api/v1/rootfolder/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single root folder by id.'},
 {'name': 'lidarr_update_rootfolder',
  'method': 'PUT',
  'path': '/api/v1/rootfolder/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update a root folder. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_delete_rootfolder',
  'method': 'DELETE',
  'path': '/api/v1/rootfolder/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete a root folder (does not delete library files). DESTRUCTIVE: this deletes data.'},
 {'name': 'lidarr_search',
  'method': 'GET',
  'path': '/api/v1/search',
  'pp': [],
  'qp': [{'name': 'term', 'wire': 'term', 'type': 'str', 'default': 'None'}],
  'bk': 'none',
  'doc': 'Search across artists, albums, and tracks by term. Query params: term.'},
 {'name': 'lidarr_get_system_status',
  'method': 'GET',
  'path': '/api/v1/system/status',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get server status (version, app data, os).'},
 {'name': 'lidarr_get_system_routes',
  'method': 'GET',
  'path': '/api/v1/system/routes',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get all registered API routes.'},
 {'name': 'lidarr_get_system_routes_duplicate',
  'method': 'GET',
  'path': '/api/v1/system/routes/duplicate',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get duplicate API routes.'},
 {'name': 'lidarr_restart_lidarr',
  'method': 'POST',
  'path': '/api/v1/system/restart',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Restart Lidarr. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_shutdown_lidarr',
  'method': 'POST',
  'path': '/api/v1/system/shutdown',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Shut down Lidarr. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_list_system_backup',
  'method': 'GET',
  'path': '/api/v1/system/backup',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List system backups.'},
 {'name': 'lidarr_delete_system_backup',
  'method': 'DELETE',
  'path': '/api/v1/system/backup/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete a system backup. DESTRUCTIVE: this deletes data.'},
 {'name': 'lidarr_restore_backup',
  'method': 'POST',
  'path': '/api/v1/system/backup/restore/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Restore from an existing backup. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_restore_backup_upload',
  'method': 'POST',
  'path': '/api/v1/system/backup/restore/upload',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Restore from an uploaded backup zip. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_get_system_task',
  'method': 'GET',
  'path': '/api/v1/system/task',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List scheduler tasks.'},
 {'name': 'lidarr_get_system_task_by_id',
  'method': 'GET',
  'path': '/api/v1/system/task/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single scheduler task by id.'},
 {'name': 'lidarr_list_tag',
  'method': 'GET',
  'path': '/api/v1/tag',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List tags.'},
 {'name': 'lidarr_create_tag',
  'method': 'POST',
  'path': '/api/v1/tag',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create a tag. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_get_tag',
  'method': 'GET',
  'path': '/api/v1/tag/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single tag by id.'},
 {'name': 'lidarr_update_tag',
  'method': 'PUT',
  'path': '/api/v1/tag/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Rename a tag. WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_delete_tag',
  'method': 'DELETE',
  'path': '/api/v1/tag/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete a tag. DESTRUCTIVE: this deletes data.'},
 {'name': 'lidarr_list_tag_detail',
  'method': 'GET',
  'path': '/api/v1/tag/detail',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Tag usage summary across all entities.'},
 {'name': 'lidarr_get_tag_detail',
  'method': 'GET',
  'path': '/api/v1/tag/detail/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Tag usage summary for a single tag.'},
 {'name': 'lidarr_list_track',
  'method': 'GET',
  'path': '/api/v1/track',
  'pp': [],
  'qp': [{'name': 'artist_id', 'wire': 'artistId', 'type': 'int', 'default': 'None'}, {'name': 'album_id', 'wire': 'albumId', 'type': 'int', 'default': 'None'}, {'name': 'album_release_id', 'wire': 'albumReleaseId', 'type': 'int', 'default': 'None'}, {'name': 'track_ids', 'wire': 'trackIds', 'type': 'list[Any]', 'default': 'None'}],
  'bk': 'none',
  'doc': 'List tracks, optionally filtered by artist or album. Query params: artist_id, album_id.'},
 {'name': 'lidarr_get_track',
  'method': 'GET',
  'path': '/api/v1/track/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single track by id.'},
 {'name': 'lidarr_list_trackfile',
  'method': 'GET',
  'path': '/api/v1/trackfile',
  'pp': [],
  'qp': [{'name': 'artist_id', 'wire': 'artistId', 'type': 'int', 'default': 'None'}, {'name': 'track_file_ids', 'wire': 'trackFileIds', 'type': 'list[Any]', 'default': 'None'}, {'name': 'album_id', 'wire': 'albumId', 'type': 'list[Any]', 'default': 'None'}, {'name': 'unmapped', 'wire': 'unmapped', 'type': 'bool', 'default': 'False'}],
  'bk': 'none',
  'doc': 'List track files, optionally filtered by artist or album. Query params: artist_id, album_id.'},
 {'name': 'lidarr_get_trackfile',
  'method': 'GET',
  'path': '/api/v1/trackfile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single track file by id.'},
 {'name': 'lidarr_update_trackfile',
  'method': 'PUT',
  'path': '/api/v1/trackfile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update a track file (quality, tags). WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_bulk_edit_trackfile',
  'method': 'PUT',
  'path': '/api/v1/trackfile/editor',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk update track files (body is a list of resources). WRITE: this modifies your Lidarr instance.'},
 {'name': 'lidarr_delete_trackfile',
  'method': 'DELETE',
  'path': '/api/v1/trackfile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete a track file. DESTRUCTIVE: this deletes data.'},
 {'name': 'lidarr_bulk_delete_trackfile',
  'method': 'DELETE',
  'path': '/api/v1/trackfile/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk delete track files (body carries track file ids). DESTRUCTIVE: this deletes data.'},
 {'name': 'lidarr_list_update',
  'method': 'GET',
  'path': '/api/v1/update',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List available application updates.'},
 {'name': 'lidarr_list_wanted_missing',
  'method': 'GET',
  'path': '/api/v1/wanted/missing',
  'pp': [],
  'qp': [{'name': 'page', 'wire': 'page', 'type': 'int', 'default': '1'}, {'name': 'page_size', 'wire': 'pageSize', 'type': 'int', 'default': '10'}, {'name': 'sort_key', 'wire': 'sortKey', 'type': 'str', 'default': '""'}, {'name': 'sort_direction', 'wire': 'sortDirection', 'type': 'str', 'default': '""'}, {'name': 'include_artist', 'wire': 'includeArtist', 'type': 'bool', 'default': 'False'}, {'name': 'monitored', 'wire': 'monitored', 'type': 'bool', 'default': 'True'}],
  'bk': 'none',
  'doc': 'Missing albums page. Query params: page, page_size, sort_key, sort_direction, include_artist, monitored.'},
 {'name': 'lidarr_get_wanted_missing',
  'method': 'GET',
  'path': '/api/v1/wanted/missing/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single missing album by id.'},
 {'name': 'lidarr_list_wanted_cutoff',
  'method': 'GET',
  'path': '/api/v1/wanted/cutoff',
  'pp': [],
  'qp': [{'name': 'page', 'wire': 'page', 'type': 'int', 'default': '1'}, {'name': 'page_size', 'wire': 'pageSize', 'type': 'int', 'default': '10'}, {'name': 'sort_key', 'wire': 'sortKey', 'type': 'str', 'default': '""'}, {'name': 'sort_direction', 'wire': 'sortDirection', 'type': 'str', 'default': '""'}, {'name': 'include_artist', 'wire': 'includeArtist', 'type': 'bool', 'default': 'False'}, {'name': 'monitored', 'wire': 'monitored', 'type': 'bool', 'default': 'True'}],
  'bk': 'none',
  'doc': 'Cutoff-unmet albums page. Query params: page, page_size, sort_key, sort_direction, include_artist, monitored.'},
 {'name': 'lidarr_get_wanted_cutoff',
  'method': 'GET',
  'path': '/api/v1/wanted/cutoff/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single cutoff-unmet album by id.'},
]

# GROUPS
_GROUPS: dict[str, tuple[str, ...]] = {
    "lidarr_media_library": (
        'lidarr_add_album',
        'lidarr_add_artist',
        'lidarr_bulk_delete_artist',
        'lidarr_bulk_delete_trackfile',
        'lidarr_bulk_edit_trackfile',
        'lidarr_bulk_update_artist',
        'lidarr_delete_album',
        'lidarr_delete_artist',
        'lidarr_delete_trackfile',
        'lidarr_get_album',
        'lidarr_get_artist',
        'lidarr_get_rename',
        'lidarr_get_retag',
        'lidarr_get_track',
        'lidarr_get_trackfile',
        'lidarr_list_album',
        'lidarr_list_artist',
        'lidarr_list_track',
        'lidarr_list_trackfile',
        'lidarr_lookup_album',
        'lidarr_lookup_artist',
        'lidarr_monitor_album',
        'lidarr_update_album',
        'lidarr_update_albumstudio',
        'lidarr_update_artist',
        'lidarr_update_trackfile',
    ),
    "lidarr_calendar": (
        'lidarr_get_calendar',
        'lidarr_list_calendar',
    ),
    "lidarr_wanted": (
        'lidarr_get_wanted_cutoff',
        'lidarr_get_wanted_missing',
        'lidarr_list_wanted_cutoff',
        'lidarr_list_wanted_missing',
    ),
    "lidarr_history_blocklist": (
        'lidarr_bulk_delete_blocklist',
        'lidarr_delete_blocklist',
        'lidarr_list_blocklist',
        'lidarr_list_history',
        'lidarr_list_history_artist',
        'lidarr_list_history_since',
        'lidarr_mark_history_item_failed',
    ),
    "lidarr_queue": (
        'lidarr_bulk_delete_queue',
        'lidarr_commit_manual_import',
        'lidarr_delete_queue',
        'lidarr_get_queue_details',
        'lidarr_get_queue_status',
        'lidarr_grab_queue_bulk',
        'lidarr_grab_queue_item',
        'lidarr_list_manualimport',
        'lidarr_list_queue',
    ),
    "lidarr_release_search": (
        'lidarr_download_release',
        'lidarr_get_parse',
        'lidarr_list_release',
        'lidarr_push_release',
        'lidarr_search',
    ),
    "lidarr_system_commands": (
        'lidarr_delete_command',
        'lidarr_delete_system_backup',
        'lidarr_get_command',
        'lidarr_get_diskspace',
        'lidarr_get_health',
        'lidarr_get_system_routes',
        'lidarr_get_system_routes_duplicate',
        'lidarr_get_system_status',
        'lidarr_get_system_task',
        'lidarr_get_system_task_by_id',
        'lidarr_list_command',
        'lidarr_list_localization',
        'lidarr_list_log',
        'lidarr_list_log_file',
        'lidarr_list_log_file_update',
        'lidarr_list_system_backup',
        'lidarr_list_update',
        'lidarr_ping',
        'lidarr_restart_lidarr',
        'lidarr_restore_backup',
        'lidarr_restore_backup_upload',
        'lidarr_run_command',
        'lidarr_shutdown_lidarr',
    ),
    "lidarr_config": (
        'lidarr_get_config_downloadclient',
        'lidarr_get_config_downloadclient_by_id',
        'lidarr_get_config_host',
        'lidarr_get_config_host_by_id',
        'lidarr_get_config_indexer',
        'lidarr_get_config_indexer_by_id',
        'lidarr_get_config_mediamanagement',
        'lidarr_get_config_mediamanagement_by_id',
        'lidarr_get_config_metadataprovider',
        'lidarr_get_config_metadataprovider_by_id',
        'lidarr_get_config_naming',
        'lidarr_get_config_naming_by_id',
        'lidarr_get_config_ui',
        'lidarr_get_config_ui_by_id',
        'lidarr_list_config_naming_examples',
        'lidarr_list_filesystem',
        'lidarr_list_filesystem_mediafiles',
        'lidarr_list_filesystem_type',
        'lidarr_update_config_downloadclient',
        'lidarr_update_config_host',
        'lidarr_update_config_indexer',
        'lidarr_update_config_mediamanagement',
        'lidarr_update_config_metadataprovider',
        'lidarr_update_config_naming',
        'lidarr_update_config_ui',
    ),
    "lidarr_indexers": (
        'lidarr_action_indexer',
        'lidarr_bulk_delete_indexer',
        'lidarr_bulk_update_indexer',
        'lidarr_create_delayprofile',
        'lidarr_create_indexer',
        'lidarr_create_releaseprofile',
        'lidarr_delete_delayprofile',
        'lidarr_delete_indexer',
        'lidarr_delete_releaseprofile',
        'lidarr_get_delayprofile',
        'lidarr_get_indexer',
        'lidarr_get_indexer_schema',
        'lidarr_get_indexerflag',
        'lidarr_get_releaseprofile',
        'lidarr_list_delayprofile',
        'lidarr_list_indexer',
        'lidarr_list_releaseprofile',
        'lidarr_reorder_delayprofile',
        'lidarr_test_all_indexer',
        'lidarr_test_indexer',
        'lidarr_update_delayprofile',
        'lidarr_update_indexer',
        'lidarr_update_releaseprofile',
    ),
    "lidarr_import_lists": (
        'lidarr_action_importlist',
        'lidarr_bulk_delete_importlist',
        'lidarr_bulk_update_importlist',
        'lidarr_create_importlist',
        'lidarr_create_importlistexclusion',
        'lidarr_delete_importlist',
        'lidarr_delete_importlistexclusion',
        'lidarr_get_importlist',
        'lidarr_get_importlist_schema',
        'lidarr_get_importlistexclusion',
        'lidarr_list_importlist',
        'lidarr_list_importlistexclusion',
        'lidarr_test_all_importlist',
        'lidarr_test_importlist',
        'lidarr_update_importlist',
        'lidarr_update_importlistexclusion',
    ),
    "lidarr_download_clients": (
        'lidarr_action_downloadclient',
        'lidarr_bulk_delete_downloadclient',
        'lidarr_bulk_update_downloadclient',
        'lidarr_create_downloadclient',
        'lidarr_delete_downloadclient',
        'lidarr_get_downloadclient',
        'lidarr_get_downloadclient_schema',
        'lidarr_list_downloadclient',
        'lidarr_test_all_downloadclient',
        'lidarr_test_downloadclient',
        'lidarr_update_downloadclient',
    ),
    "lidarr_notifications_metadata": (
        'lidarr_action_metadata',
        'lidarr_action_notification',
        'lidarr_create_metadata',
        'lidarr_create_notification',
        'lidarr_delete_metadata',
        'lidarr_delete_notification',
        'lidarr_get_metadata',
        'lidarr_get_metadata_schema',
        'lidarr_get_notification',
        'lidarr_get_notification_schema',
        'lidarr_list_metadata',
        'lidarr_list_notification',
        'lidarr_test_all_metadata',
        'lidarr_test_all_notification',
        'lidarr_test_metadata',
        'lidarr_test_notification',
        'lidarr_update_metadata',
        'lidarr_update_notification',
    ),
    "lidarr_storage": (
        'lidarr_create_remotepathmapping',
        'lidarr_create_rootfolder',
        'lidarr_delete_remotepathmapping',
        'lidarr_delete_rootfolder',
        'lidarr_get_remotepathmapping',
        'lidarr_get_rootfolder',
        'lidarr_list_remotepathmapping',
        'lidarr_list_rootfolder',
        'lidarr_update_remotepathmapping',
        'lidarr_update_rootfolder',
    ),
    "lidarr_tags": (
        'lidarr_create_autotagging',
        'lidarr_create_customfilter',
        'lidarr_create_tag',
        'lidarr_delete_autotagging',
        'lidarr_delete_customfilter',
        'lidarr_delete_tag',
        'lidarr_get_autotagging',
        'lidarr_get_autotagging_schema',
        'lidarr_get_customfilter',
        'lidarr_get_tag',
        'lidarr_get_tag_detail',
        'lidarr_list_autotagging',
        'lidarr_list_customfilter',
        'lidarr_list_tag',
        'lidarr_list_tag_detail',
        'lidarr_update_autotagging',
        'lidarr_update_customfilter',
        'lidarr_update_tag',
    ),
    "lidarr_profiles_formats": (
        'lidarr_bulk_delete_customformat',
        'lidarr_bulk_update_customformat',
        'lidarr_create_customformat',
        'lidarr_create_metadataprofile',
        'lidarr_create_qualityprofile',
        'lidarr_delete_customformat',
        'lidarr_delete_metadataprofile',
        'lidarr_delete_qualityprofile',
        'lidarr_get_customformat',
        'lidarr_get_customformat_schema',
        'lidarr_get_language',
        'lidarr_get_metadataprofile',
        'lidarr_get_metadataprofile_schema',
        'lidarr_get_qualitydefinition',
        'lidarr_get_qualityprofile',
        'lidarr_get_qualityprofile_schema',
        'lidarr_list_customformat',
        'lidarr_list_language',
        'lidarr_list_metadataprofile',
        'lidarr_list_qualitydefinition',
        'lidarr_list_qualityprofile',
        'lidarr_update_customformat',
        'lidarr_update_metadataprofile',
        'lidarr_update_quality_definitions',
        'lidarr_update_qualitydefinition',
        'lidarr_update_qualityprofile',
    ),
}



def _tool_source(spec: dict[str, Any]) -> str:
    parts: list[str] = []
    for p in spec["pp"]:
        parts.append(f"{p['name']}: {p['type']}")
    for q in spec["qp"]:
        parts.append(f"{q['name']}: {q['type']} = {q['default']}")
    if spec["bk"] == "dict":
        parts.append("body: dict[str, Any] = {}")
    elif spec["bk"] == "list":
        parts.append("body: list[Any] = []")
    sig = ", ".join(parts)

    path_tmpl = spec["path"]
    for p in spec["pp"]:
        path_tmpl = path_tmpl.replace("{" + p["wire"] + "}", "{" + p["name"] + "}")
    if spec["pp"]:
        arg_call = ", ".join(f"{p['name']}=quote(str({p['name']}))" for p in spec["pp"])
        url_expr = f'f"{path_tmpl}".format({arg_call})'
    else:
        url_expr = repr(spec["path"])

    if spec["qp"]:
        params_expr = "_omit({" + ", ".join(f'"{q["wire"]}": {q["name"]}' for q in spec["qp"]) + "})"
    else:
        params_expr = "None"
    json_expr = "body" if spec["bk"] != "none" else "None"

    doc = spec["doc"].replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    return (
        f"async def {spec['name']}({sig}) -> JSONVal:\n"
        f'    """{doc}"""\n'
        f"    return await _req({spec['method']!r}, {url_expr}, params={params_expr}, json_body={json_expr})\n"
    )


def _op_line(name: str, fn: Any) -> str:
    """One line of a group tool's description: signature + one-line doc."""
    sig = ", ".join(
        p.name if p.default is inspect.Parameter.empty else f"{p.name}={p.default!r}"
        for p in inspect.signature(fn).parameters.values()
    )
    return f"- {name}({sig}) — {' '.join((fn.__doc__ or '').split())}"


def _register_group(group: str, names: tuple[str, ...], ns: dict[str, Any], method_of: dict[str, str]) -> None:
    """Register one dispatching tool that fans out to every endpoint function
    named in `names`. The endpoint functions themselves are untouched -
    they're just looked up by name instead of each becoming its own tool."""
    fns = {n: ns[n] for n in names}

    async def dispatch(operation: str, arguments: JSONObj | None = None) -> JSONVal:
        fn = fns.get(operation)
        if fn is None:
            raise ToolError(f"Unknown operation {operation!r} for {group}. Valid: {', '.join(fns)}")
        return await fn(**(arguments or {}))

    dispatch.__annotations__["operation"] = Literal[names]
    ann = READONLY if {method_of[n] for n in names} == {"GET"} else None
    mcp.add_tool(
        Tool.from_function(
            dispatch,
            name=group,
            description=(
                f"{group.replace('_', ' ')} operations on Lidarr. Pass `operation` and an "
                f"`arguments` dict matching that operation's parameters.\n\n"
                + "\n".join(_op_line(n, f) for n, f in fns.items())
            ),
            annotations=ann,
        )
    )


def register_tools() -> None:
    src = "\n".join(_tool_source(spec) for spec in _TOOL_REGISTRY)
    ns: dict[str, Any] = {}
    exec(src, globals(), ns)
    method_of = {spec["name"]: spec["method"] for spec in _TOOL_REGISTRY}
    for group, names in _GROUPS.items():
        _register_group(group, names, ns, method_of)


register_tools()


def main() -> None:
    global _client
    url = os.environ.get("LIDARR_URL")
    if not url:
        print("LIDARR_URL environment variable is required (e.g. http://lidarr.example.com)", file=sys.stderr)
        raise SystemExit(1)
    _client = build_client(url, os.environ.get("LIDARR_API_KEY"))
    mcp.run()


if __name__ == "__main__":
    main()
